### PR TITLE
Add instructions for running the scrapper without docker

### PR DESCRIPTION
**Pull request by kerollaine**
I've found this to be quite useful, specially for beginners, but I don't know if there is a better way to debug without ditching Docker, so feel free to close without merging if that is the case.

### CODE REVIEW

**Comment by Irio** [comment]
I feel that maintaining multiple instructions at this time of the project might take too much effort, rather than having a single way of running everything, which is heavily tested by all contributors (I would personally use Conda environments if not using Docker, for instance).

Did you have any trouble running the project using Docker?

**Comment by brunolellis** [comment]
A simple way to run the spider locally:
1. Install `requirements.txt`
2. Comment lines 7 and 8 in `settings.py` (both 'gazette.pipelines')
3. Run `scrapy crawl sp_campinas` or another spider

I don't know if it is the best way since I am not from python world, but I hope it helps :grinning:

**Comment by stefersonferreira** [comment]
In windows you will need to install the pywin32.

use `pip install pypiwin32`

**Comment by kerollaine** [comment]
I have no problems running the project using Docker, I just think it is easier to debug or test parts of the code without docker. 
But I agree with you, it's important to keep the project setup as simple as possible.
Thank you very much for the feedback!

**Comment by Irio** [comment]
@kerollaine I believe we can have the best of both worlds if I enable the wiki and let everyone edit it so this documentation can be maintained by the community, adding a reference in the README file. How about that?

**Comment by kerollaine** [comment]
@Irio the way that @brunolellis explained is simple and works very well too. So I think this is unnecessary for now, as each contributor can find their preferred way to achieve this by their own. Additionally wiki maintenance can become difficult over time, IMO.

**Pull request closed without merging**
