### PR TITLE
Add spider for Manaus/AM

### PR DESCRIPTION
**Pull request by alfakini**
Hey people,

In this PR we add the spider to collect data from [Manaus/AM gazette](http://dom.manaus.am.gov.br/diario-oficial-de-manaus/).

### CODE REVIEW

**Comment by alfakini** [comment]
@rennerocha Added the check for the extra edition. Thanks for the catch 👍

**Comment by giovanisleite** [comment]
Remember to update the [cities.md](https://github.com/okfn-brasil/diario-oficial/blob/master/CITIES.md)

**Comment by alfakini** [comment]
@giovanisleite @Irio Should we add in the same spider the executive and legislative? Seems to me that in the cases we have gazettes for each power we should add different spiders. What about `am_manaus_executive.py` and `am_manaus_legislative.py`?

**Comment by giovanisleite** [comment]
I agree that we need two spiders, @alfakini, but just in case of two different websites (that is the case here) and keep only one spider for two separated powers if it is in the same site like rs_porto_alegre, what do you think?

**Comment by Irio** [comment]
In a project (hopefully, in a few months) with hundreds of crawlers, would be easier to handle a maximum of one spider per municipality.

You could make them work by putting two elements in both `allowed_domains` and `start_urls`. Let me know if you need further instructions on how to do it.

**Comment by rennerocha** [comment]
As both will return the same type of item `GazetteItem`, I'd suggest stop using the `start_urls` and write a `start_requests` method and then send the respective requests for each power with two separated callbacks: `parse_executive` (it will be the actual `parse`) and `parse_legislative`.

**Comment by alfakini** [comment]
@Irio @giovanisleite @rennerocha Implemented the crawler for the legislative power. Thanks @rennerocha for the suggestion 👍

**Pull request merged**
